### PR TITLE
Breaking down fbranch into smaller chunks [redoing Niall McCrann's fbranch-1]

### PR DESCRIPTION
**Pull request by msyriac**
Let's try this again.

### CODE REVIEW

**Comment by NiallMac** [comment]
Thanks @msyriac  - good point about the hard-coded paths. I had added `mask_path` entry to the config file, but forgotten to push that - should we stick with your solution or have separate data_path and mask_path? Any other comments before we merge?

**Comment by msyriac** [comment]
I prefer having the number of paths not proliferate. One can always symlink stuff into data_path.

**Comment by msyriac** [comment]
I'll merge this soon.

**Comment by NiallMac** [comment]
While we're discussing I'm not actually positive what `signal_path` and `data_path` are intended for. I think the former is where a_lms for simulations are stored? And the latter is a general output directory? 

On a different note, how do we want to organize the rdn0 functions? I would assume we want to have a class method that does rdn0, which could just internally call one or more of the existing functions in solenspipe.py or bias.py. These existing functions seem to be in two different places at the moment (solenspipe.py or bias.py) - should we consolidate them in just one of those places? @qujia7 maybe you know which are the most up-to-date/useful of these?

**Comment by msyriac** [comment]
Right, we don't / shouldn't have write access to `signal_path` since it has pre-calculated expensive sims. `data_path` is more like a scratch space.

The rdn0 function in bias.py is actually an implementation of "MCMC RDN0", while the diagonal rdn0 Frank added are (semi-) analytic. But I agree that any rdn0 related stuff should be in bias.py, not solenspipe.py. Feel free to move.

**Comment by NiallMac** [comment]
Ok, thanks Mat. I was thinking we could make tidying up the rdn0 stuff the next pull request, so I'll wait to get this one merged before moving stuff around on this branch.

**Pull request merged**
